plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\TPRADHA\\OneDrive - Daimler Truck\\Workspace\\Documents\\Docs\\Personal\\PetProject\\receipts-app\\frontend\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "C:\\Users\\TPRADHA\\OneDrive - Daimler Truck\\Workspace\\Documents\\Docs\\Personal\\PetProject\\receipts-app\\frontend"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]